from django.db import models
from leads.models import Lead

class AgentTaskLog(models.Model):
    """Tracks every action taken by an agent for audit and cost control."""
    AGENT_NAMES = [
        ('FETCH', 'Lead Fetch Agent'),
        ('RESEARCH', 'Research & Ranking Agent'),
        ('PERSONA', 'Persona Agent'),
        ('SCRIPT', 'Script Generator'),
        # ... add others as we build them
    ]

    lead = models.ForeignKey(Lead, on_delete=models.CASCADE, related_name='ai_logs')
    agent_name = models.CharField(max_length=50, choices=AGENT_NAMES)
    status = models.CharField(max_length=20, default='processing') # processing, completed, failed
    
    # The 'thought process' or raw output from Gemini
    internal_monologue = models.TextField(blank=True, null=True) 
    output_data = models.JSONField(default=dict, blank=True)
    
    # Cost Tracking
    prompt_tokens = models.IntegerField(default=0)
    completion_tokens = models.IntegerField(default=0)
    total_cost = models.DecimalField(max_digits=10, decimal_places=6, default=0)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.agent_name} - {self.lead.email} ({self.status})"

class LeadIntelligence(models.Model):
    """Stores the 'Rich Knowledge' generated by the brain about a lead."""
    lead = models.OneToOneField(Lead, on_delete=models.CASCADE, related_name='intelligence')
    
    # Brain Output
    score = models.IntegerField(default=0) # 0-100 ranking
    persona_tag = models.CharField(max_length=100, blank=True, null=True)
    conversion_probability = models.FloatField(default=0.0)
    
    # Strategic Insights
    suggested_approach = models.TextField(blank=True, null=True)
    generated_script = models.TextField(blank=True, null=True)
    
    last_processed = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Intelligence: {self.lead.first_name} (Score: {self.score})"

class AIAgent(models.Model):
    """Defines an AI Agent identity and its factory-default instructions."""
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True, null=True)
    base_instruction = models.TextField()
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class AgentInstructionTune(models.Model):
    """Incremental instruction updates that append to the base instructions."""
    agent = models.ForeignKey(AIAgent, on_delete=models.CASCADE, related_name='tuning_history')
    additional_instructions = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Tune for {self.agent.name} at {self.created_at}"