# Generated by Django 5.2.12 on 2026-04-04 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('category', models.CharField(choices=[('SALES', 'Sales Lead'), ('POTENTIAL', 'Potential Lead'), ('SOCIAL', 'Social Media Lead'), ('WEBINAR', 'Webinar Lead')], max_length=20)),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.CharField(blank=True, help_text='MM/YY', max_length=10, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='courses.program')),
            ],
        ),
    ]
