# Generated by Django 5.2.12 on 2026-04-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='platform',
            field=models.CharField(choices=[('FB', 'Facebook'), ('IG', 'Instagram'), ('LI', 'LinkedIn'), ('TT', 'TikTok'), ('NA', 'N/A')], default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.CharField(choices=[('PARTICIPANT', 'Course Participant'), ('SOCIAL', 'Social Media Lead'), ('WEBINAR', 'Webinar Lead')], max_length=20),
        ),
    ]
