# Generated by Django 4.2.23 on 2026-04-25 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_program_learning_outcomes_program_knowledge_and_more'),
        ('leads', '0002_lead_platform_alter_lead_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_platform', models.CharField(blank=True, max_length=50, null=True)),
                ('total_count', models.IntegerField(default=0)),
                ('is_discovery', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='category',
            field=models.CharField(choices=[('PARTICIPANT', 'Course Participant'), ('SOCIAL', 'Social Media Lead'), ('WEBINAR', 'Webinar Lead'), ('CAMPAIGN', 'Campaign Lead')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='platform',
            field=models.CharField(choices=[('FB', 'Facebook'), ('IG', 'Instagram'), ('LI', 'LinkedIn'), ('TT', 'TikTok'), ('EXT_REF', 'External Referral'), ('INT_REF', 'Internal Referral'), ('ORG_REF', 'Organizational Referral'), ('NA', 'N/A')], default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='courses.program'),
        ),
        migrations.AddField(
            model_name='lead',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadimportbatch'),
        ),
    ]
