# Generated by Django 4.2.23 on 2026-04-24 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_remove_program_learning_outcomes_program_knowledge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('NGO', 'NGO'), ('CORP', 'Corporate'), ('GOV', 'Government'), ('ACAD', 'Academic'), ('DEV', 'Development Partner')], max_length=10)),
                ('academic_levels', models.JSONField(blank=True, default=list, help_text='Multi-select: pre-primary, primary, secondary, tertiary, vocational')),
                ('country', models.CharField(max_length=100)),
                ('hq_location', models.CharField(max_length=255)),
                ('branches', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('year_established', models.IntegerField(blank=True, null=True)),
                ('size_range', models.CharField(help_text='e.g., 1-50, 50-200, 500+', max_length=50)),
                ('beneficiary_reach', models.CharField(blank=True, max_length=255, null=True)),
                ('thematic_areas', models.TextField(help_text='e.g., ECD, Mental Health, Education')),
                ('strategic_priorities', models.TextField(blank=True, null=True)),
                ('challenges', models.TextField(blank=True, null=True)),
                ('capacity_gaps', models.TextField(blank=True, null=True)),
                ('funding_status', models.CharField(choices=[('DONOR', 'Donor-funded'), ('SELF', 'Self-funded'), ('GRANT', 'Grant cycle stage')], default='SELF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='B2BMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propensity_score', models.IntegerField(default=0)),
                ('campaign_strategy', models.TextField()),
                ('pitching_pointers', models.JSONField(default=list)),
                ('match_reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='b2b.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.program')),
            ],
            options={
                'verbose_name_plural': 'B2B Matches',
            },
        ),
    ]
