# Generated by Django 5.2.12 on 2026-04-07 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_lead_platform_alter_lead_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('FETCH', 'Lead Fetch Agent'), ('RESEARCH', 'Research & Ranking Agent'), ('PERSONA', 'Persona Agent'), ('SCRIPT', 'Script Generator')], max_length=50)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('internal_monologue', models.TextField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('persona_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('conversion_probability', models.FloatField(default=0.0)),
                ('suggested_approach', models.TextField(blank=True, null=True)),
                ('generated_script', models.TextField(blank=True, null=True)),
                ('last_processed', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence', to='leads.lead')),
            ],
        ),
    ]
