# Generated by Django 5.2.12 on 2026-04-03 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('SHORT', 'Short/Certificate Course'), ('POSTGRAD', 'Postgraduate Program')], max_length=10)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('target_audience', models.TextField(blank=True, null=True, verbose_name='Who is this for?')),
                ('duration_tuition_fee', models.TextField(blank=True, null=True, verbose_name='Duration & Fees (Markdown)')),
                ('overview', models.TextField(blank=True, null=True)),
                ('learning_outcomes', models.JSONField(blank=True, default=list)),
                ('skills_competencies', models.TextField(blank=True, null=True)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('number_of_sessions', models.IntegerField(blank=True, null=True)),
                ('degree_type', models.CharField(choices=[('MSC', 'M.Sc'), ('MED', 'M.Ed'), ('MBA', 'MBA'), ('NONE', 'None (Certificate)')], default='NONE', max_length=10)),
                ('about_programme', models.TextField(blank=True, null=True)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('program_structure', models.TextField(blank=True, null=True, verbose_name='Program Structure (Markdown)')),
                ('assessment_details', models.TextField(blank=True, null=True)),
                ('unique_features', models.JSONField(blank=True, default=list)),
                ('admission_requirements', models.JSONField(blank=True, default=list)),
                ('teaching_learning', models.TextField(blank=True, null=True)),
                ('admission_test_details', models.TextField(blank=True, null=True)),
                ('career_prospects', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.program')),
            ],
        ),
    ]
