# Generated by Django 5.2.12 on 2026-04-07 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='learning_outcomes',
        ),
        migrations.AddField(
            model_name='program',
            name='knowledge',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='admission_requirements',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='degree_type',
            field=models.CharField(blank=True, choices=[('MSC', 'M.Sc'), ('MED', 'M.Ed'), ('MBA', 'MBA'), ('NONE', 'None (Certificate)')], default='NONE', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration_tuition_fee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='objectives',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_structure',
            field=models.TextField(blank=True, help_text='Markdown supported', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='skills_competencies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='target_audience',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='topics',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='unique_features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.program'),
        ),
    ]
