# Generated by Django 5.2.12 on 2026-04-07 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_remove_program_learning_outcomes_program_knowledge_and_more'),
        ('leads', '0002_lead_platform_alter_lead_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('batch', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='courses.program')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INITIATE', 'Need to Initiate'), ('FOLLOWUP', 'Needs Follow-up'), ('CONVERTED', 'Converted'), ('NOT_CONVERTED', 'Not Converted')], default='INITIATE', max_length=20)),
                ('user_rating', models.IntegerField(default=0)),
                ('ai_score', models.IntegerField(default=0)),
                ('ai_persona', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_leads', to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='leads.lead')),
            ],
            options={
                'unique_together': {('campaign', 'lead')},
            },
        ),
    ]
